package com.nova.engine

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.view.MotionEvent
import android.view.View
import kotlin.math.max

/** Touch-first production editor surface: hierarchy, viewport, inspector, assets and console. */
class NovaEditorView(context: Context) : View(context) {
    private val p=Paint(Paint.ANTI_ALIAS_FLAG); private val tx=Paint(Paint.ANTI_ALIAS_FLAG)
    private val project=EditorProject().apply{seedDemoContent()}
    private val nodes=mutableListOf(
        EditorEntity(1,"Player",300f,170f,96f,96f,tag="CharacterBody2D"),
        EditorEntity(2,"Ground",220f,380f,520f,64f,layer=-1,textureId="tiles",tag="StaticBody2D"),
        EditorEntity(3,"PointLight2D",590f,125f,48f,48f,layer=2,tag="Light2D"),
        EditorEntity(4,"Camera2D",330f,190f,32f,32f,layer=3,tag="Camera2D"))
    private val profiler=FrameProfiler(); private var selected=1; private var playing=false; private var dragging=false; private var dx=0f; private var dy=0f; private var message="Ready — Nova Editor"
    private val bg=Color.rgb(13,16,22); private val panel=Color.rgb(24,28,36); private val panel2=Color.rgb(31,36,45); private val line=Color.rgb(49,55,66); private val accent=Color.rgb(70,145,255); private val fg=Color.rgb(230,234,241); private val muted=Color.rgb(145,154,168); private val good=Color.rgb(105,205,140)
    init{isFocusable=true;setBackgroundColor(bg)}

    override fun onDraw(c:Canvas){val st=System.nanoTime();c.drawColor(bg);val w=width.toFloat();val h=height.toFloat();top(c,w);val left=238f;val right=300f;val bottom=150f;viewport(c,left,50f,w-right,h-bottom);leftPanel(c,0f,50f,left,h-bottom);inspector(c,w-right,50f,w,h-bottom);console(c,left,h-bottom,w-right,h);profiler.record((System.nanoTime()-st)/1e6f);postInvalidateOnAnimation()}
    private fun top(c:Canvas,w:Float){p.color=panel;c.drawRect(0f,0f,w,50f,p);txt(c,"NOVA",14f,32f,16f,fg,true);txt(c,"2D",68f,31f,12f,accent,true);button(c,98f,9f,48f,32f,"☰",false);button(c,152f,9f,48f,32f,"▣",false);button(c,206f,9f,48f,32f,"↶",false);button(c,260f,9f,48f,32f,"↷",false);button(c,318f,7f,72f,36f,if(playing)"■ STOP" else "▶ PLAY",playing);button(c,396f,9f,48f,32f,"Ⅱ",false);button(c,450f,9f,52f,32f,"SAVE",false);txt(c,if(playing)"PLAY MODE" else "EDITOR",max(520f,w-190f),31f,11f,if(playing)good else muted,true)}
    private fun leftPanel(c:Canvas,l:Float,top:Float,r:Float,b:Float){p.color=panel;c.drawRect(l,top,r,b,p);txt(c,"SCENE",14f,top+27f,11f,muted,true);button(c,r-68f,top+10f,28f,27f,"+",false);button(c,r-35f,top+10f,28f,27f,"⋮",false);txt(c,"▾  MainScene",15f,top+61f,13f,fg,true);var y=top+91f;nodes.forEach{e->val sel=e.id==selected;if(sel){p.color=Color.rgb(42,66,98);c.drawRect(5f,y-19f,r-5f,y+8f,p)};txt(c,if(e.visible)"●" else "○",16f,y,10f,if(e.visible)good else muted,false);txt(c,e.name,35f,y,12f,if(sel)fg else Color.rgb(195,201,210),false);txt(c,e.tag,r-104f,y,8f,muted,false);y+=29f};p.color=line;c.drawRect(0f,b-88f,r,b-87f,p);txt(c,"CREATE NODE",14f,b-64f,10f,muted,true);txt(c,"+ Sprite2D",14f,b-40f,11f,fg,false);txt(c,"+ CharacterBody2D",112f,b-40f,11f,fg,false);txt(c,"+ Camera2D",14f,b-18f,11f,fg,false);txt(c,"+ TileMap2D",112f,b-18f,11f,fg,false)}
    private fun viewport(c:Canvas,l:Float,top:Float,r:Float,b:Float){p.color=Color.rgb(17,21,28);c.drawRect(l,top,r,b,p);p.color=Color.rgb(38,44,54);p.strokeWidth=1f;var x=l;while(x<r){c.drawLine(x,top,x,b,p);x+=32f};var y=top;while(y<b){c.drawLine(l,y,r,y,p);y+=32f};txt(c,"2D VIEW",l+12f,top+22f,10f,muted,true);button(c,l+75f,top+7f,40f,28f,"↖",true);button(c,l+120f,top+7f,40f,28f,"✚",false);button(c,l+165f,top+7f,40f,28f,"↻",false);button(c,l+210f,top+7f,40f,28f,"□",false);txt(c,"100%",r-52f,top+22f,10f,muted,false);nodes.sortedBy{it.layer}.forEach{drawNode(c,it,l,top)};txt(c,message,l+12f,b-12f,10f,muted,false)}
    private fun drawNode(c:Canvas,e:EditorEntity,l:Float,top:Float){if(!e.visible)return;val x=l+e.x;val y=top+e.y;p.style=Paint.Style.FILL;p.color=when(e.tag){"CharacterBody2D"->Color.rgb(64,146,226);"StaticBody2D"->Color.rgb(83,94,110);"Light2D"->Color.rgb(236,178,63);else->Color.rgb(112,121,140)};c.drawRoundRect(RectF(x,y,x+e.width,y+e.height),8f,8f,p);if(e.tag=="CharacterBody2D"){p.color=Color.WHITE;c.drawCircle(x+e.width/2,y+30f,13f,p);p.color=Color.rgb(35,53,75);c.drawCircle(x+43f,y+28f,3f,p);c.drawCircle(x+53f,y+28f,3f,p)}else if(e.tag=="Light2D"){p.style=Paint.Style.STROKE;p.strokeWidth=2f;p.color=Color.YELLOW;c.drawCircle(x+24f,y+24f,22f,p);p.style=Paint.Style.FILL}else if(e.tag=="Camera2D"){p.style=Paint.Style.STROKE;p.strokeWidth=2f;p.color=fg;c.drawRect(x+5f,y+9f,x+27f,y+23f,p);p.style=Paint.Style.FILL};if(e.id==selected){p.style=Paint.Style.STROKE;p.strokeWidth=2f;p.color=accent;c.drawRect(x-3f,y-3f,x+e.width+3f,y+e.height+3f,p);p.style=Paint.Style.FILL;txt(c,e.name,x,y-8f,10f,accent,true)}}
    private fun inspector(c:Canvas,l:Float,top:Float,r:Float,b:Float){p.color=panel;c.drawRect(l,top,r,b,p);val e=nodes.firstOrNull{it.id==selected}?:return;txt(c,"INSPECTOR",l+14f,top+27f,11f,muted,true);txt(c,e.name,l+14f,top+58f,16f,fg,true);txt(c,e.tag,l+14f,top+76f,9f,muted,false);section(c,"TRANSFORM",l+14f,top+108f,r-14f);field(c,l+14f,top+128f,"X","%.1f".format(e.x));field(c,l+14f,top+160f,"Y","%.1f".format(e.y));field(c,l+14f,top+192f,"ROT","0.0°");section(c,"SPRITE",l+14f,top+236f,r-14f);field(c,l+14f,top+256f,"Texture",e.textureId.ifEmpty{"None"});field(c,l+14f,top+288f,"Size","${e.width.toInt()} × ${e.height.toInt()}");section(c,"RENDER",l+14f,top+332f,r-14f);field(c,l+14f,top+352f,"Z Index",e.layer.toString());field(c,l+14f,top+384f,"Visible",e.visible.toString());section(c,"PHYSICS",l+14f,top+428f,r-14f);field(c,l+14f,top+448f,"Body",if(e.tag=="StaticBody2D")"Static" else "Dynamic");section(c,"SCRIPT",l+14f,top+492f,r-14f);field(c,l+14f,top+512f,"Script","Attach…")}
    private fun console(c:Canvas,l:Float,top:Float,r:Float,b:Float){p.color=panel;c.drawRect(l,top,r,b,p);txt(c,"CONSOLE",l+13f,top+22f,10f,muted,true);txt(c,"✓ Editor initialized",l+13f,top+45f,10f,good,false);txt(c,"✓ Native C++ runtime online",l+13f,top+64f,10f,good,false);txt(c,"• MainScene   • Nodes ${nodes.size}   • Assets ${project.assets.size}",l+13f,top+83f,10f,muted,false);txt(c,"FPS %.1f | %.2f ms | %s".format(profiler.fps(),profiler.averageMs(),if(playing)"PLAY" else "EDITOR"),l+13f,top+103f,10f,muted,false);txt(c,"GLES2 | Sprite Atlas | Fixed Physics 60Hz",l+13f,top+122f,10f,muted,false)}
    private fun section(c:Canvas,s:String,x:Float,y:Float,r:Float){p.color=line;c.drawRect(x,y+8f,r,y+9f,p);txt(c,s,x,y,9f,muted,true)}
    private fun field(c:Canvas,x:Float,y:Float,n:String,v:String){txt(c,n,x,y+16f,9f,muted,false);p.color=panel2;c.drawRoundRect(x+72f,y,x+270f,y+25f,4f,4f,p);txt(c,v,x+82f,y+16f,10f,fg,false)}
    private fun txt(c:Canvas,s:String,x:Float,y:Float,size:Float,color:Int,bold:Boolean){tx.textSize=size;tx.color=color;tx.typeface=Typeface.create("sans",if(bold)Typeface.BOLD else Typeface.NORMAL);c.drawText(s,x,y,tx)}
    private fun button(c:Canvas,x:Float,y:Float,w:Float,h:Float,s:String,active:Boolean){p.color=if(active)Color.rgb(47,89,145) else panel2;c.drawRoundRect(x,y,x+w,y+h,5f,5f,p);txt(c,s,x+w/2f-tx.measureText(s)/2f,y+h/2f+4f,10f,fg,false)}
    override fun onTouchEvent(ev:MotionEvent):Boolean{val x=ev.x;val y=ev.y;val left=238f;when(ev.action){MotionEvent.ACTION_DOWN->{if(y<50f&&x in 318f..390f){playing=!playing;message=if(playing)"Play mode — runtime active" else "Stopped";invalidate();return true};if(x<left&&y>120f){val i=((y-120f)/29f).toInt();if(i in nodes.indices){selected=nodes[i].id;message="Selected ${nodes[i].name}"};invalidate();return true};if(x>=left&&x<width-300f&&y>50f&&y<height-150f){val wx=x-left;val wy=y-50f;nodes.asReversed().firstOrNull{wx>=it.x&&wx<=it.x+it.width&&wy>=it.y&&wy<=it.y+it.height}?.let{selected=it.id;dx=wx-it.x;dy=wy-it.y;dragging=true};invalidate();return true}};MotionEvent.ACTION_MOVE->{if(dragging){nodes.firstOrNull{it.id==selected}?.let{it.x=(x-left-dx).coerceIn(0f,1400f);it.y=(y-50f-dy).coerceIn(0f,900f);message="Move ${it.name}";invalidate()};return true}};MotionEvent.ACTION_UP->{dragging=false;return true}};return true}
}
