#include "nova_runtime.hpp"
namespace nova {
static float clampf(float v,float lo,float hi){return std::max(lo,std::min(hi,v));}
PhysicsWorld::PhysicsWorld()=default;
BodyId PhysicsWorld::createBody(float x,float y,BodyType t){std::lock_guard<std::mutex>g(mutex_);Body2D b;b.id=nextId_++;b.position={x,y};b.type=t;if(t==BodyType::Static){b.inverseMass=0;b.inverseInertia=0;}bodies_.push_back(b);return b.id;}
void PhysicsWorld::destroyBody(BodyId id){std::lock_guard<std::mutex>g(mutex_);for(auto&b:bodies_)if(b.id==id)b.id=INVALID_BODY;}
Body2D* PhysicsWorld::body(BodyId id){for(auto&b:bodies_)if(b.id==id)return &b;return nullptr;} const Body2D* PhysicsWorld::body(BodyId id)const{for(auto&b:bodies_)if(b.id==id)return &b;return nullptr;}
void PhysicsWorld::setVelocity(BodyId id,Vec2 v){std::lock_guard<std::mutex>g(mutex_);if(auto*b=body(id)){b->velocity=v;wake(*b);}}
void PhysicsWorld::setShapeBox(BodyId id,Vec2 s){std::lock_guard<std::mutex>g(mutex_);if(auto*b=body(id)){b->shape.type=ShapeType::Box;b->shape.size={std::max(1.f,s.x),std::max(1.f,s.y)};}}
void PhysicsWorld::setShapeCircle(BodyId id,float r){std::lock_guard<std::mutex>g(mutex_);if(auto*b=body(id)){b->shape.type=ShapeType::Circle;b->shape.radius=std::max(1.f,r);}}
void PhysicsWorld::setSensor(BodyId id,bool v){std::lock_guard<std::mutex>g(mutex_);if(auto*b=body(id))b->sensor=v;}
void PhysicsWorld::setFilter(BodyId id,std::uint32_t l,std::uint32_t m){std::lock_guard<std::mutex>g(mutex_);if(auto*b=body(id)){b->filter.layer=l;b->filter.mask=m;}}
void PhysicsWorld::setMaterial(BodyId id,float d,float f,float r){std::lock_guard<std::mutex>g(mutex_);if(auto*b=body(id)){b->material.density=std::max(.0001f,d);b->material.friction=clampf(f,0,1);b->material.restitution=clampf(r,0,1);}}
void PhysicsWorld::applyForce(BodyId id,Vec2 f){std::lock_guard<std::mutex>g(mutex_);if(auto*b=body(id);b&&b->inverseMass>0){b->force+=f;wake(*b);}}
void PhysicsWorld::applyImpulse(BodyId id,Vec2 p){std::lock_guard<std::mutex>g(mutex_);if(auto*b=body(id);b&&b->inverseMass>0){b->velocity+=p*b->inverseMass;wake(*b);}}
void PhysicsWorld::wake(Body2D&b){b.awake=true;b.sleepTime=0;}
void PhysicsWorld::integrate(Body2D&b,float dt){b.grounded=false;if(b.type==BodyType::Static||!b.awake)return;if(b.type==BodyType::Dynamic){b.velocity.y+=gravityY*dt;b.velocity+=b.force*b.inverseMass*dt;b.angularVelocity+=b.torque*b.inverseInertia*dt;}b.position+=b.velocity*dt;b.angle+=b.angularVelocity*dt;b.force={};b.torque=0;}
Aabb2D PhysicsWorld::aabb(const Body2D&b)const{if(b.shape.type==ShapeType::Circle){float r=b.shape.radius;return{{b.position.x-r,b.position.y-r},{b.position.x+r,b.position.y+r}};}Vec2 h=b.shape.size*.5f;return{{b.position.x-h.x,b.position.y-h.y},{b.position.x+h.x,b.position.y+h.y}};}
bool PhysicsWorld::canCollide(const Body2D&a,const Body2D&b)const{return a.id!=INVALID_BODY&&b.id!=INVALID_BODY&&a.id!=b.id&&((a.filter.mask&b.filter.layer)!=0)&&((b.filter.mask&a.filter.layer)!=0)&&(a.type!=BodyType::Static||b.type!=BodyType::Static);}
bool PhysicsWorld::boxBox(const Body2D&a,const Body2D&b,Contact2D&o)const{auto A=aabb(a),B=aabb(b);if(!A.overlaps(B))return false;float ox=std::min(A.max.x,B.max.x)-std::max(A.min.x,B.min.x),oy=std::min(A.max.y,B.max.y)-std::max(A.min.y,B.min.y);o.normal=(ox<oy)?Vec2{a.position.x<b.position.x? -1.f:1.f,0}:Vec2{0,a.position.y<b.position.y?-1.f:1.f};o.penetration=std::min(ox,oy);o.point={(std::max(A.min.x,B.min.x)+std::min(A.max.x,B.max.x))*.5f,(std::max(A.min.y,B.min.y)+std::min(A.max.y,B.max.y))*.5f};return true;}
bool PhysicsWorld::circleCircle(const Body2D&a,const Body2D&b,Contact2D&o)const{Vec2 d=b.position-a.position;float rr=a.shape.radius+b.shape.radius,ds=len2(d);if(ds>=rr*rr)return false;float l=std::sqrt(std::max(ds,1e-12f));o.normal=l>1e-5f?d*(1.f/l):Vec2{1,0};o.penetration=rr-l;o.point=a.position+o.normal*(a.shape.radius-o.penetration*.5f);return true;}
bool PhysicsWorld::boxCircle(const Body2D&box,const Body2D&circle,Contact2D&o)const{auto A=aabb(box);Vec2 q{clampf(circle.position.x,A.min.x,A.max.x),clampf(circle.position.y,A.min.y,A.max.y)};Vec2 d=circle.position-q;float ds=len2(d),r=circle.shape.radius;if(ds>r*r)return false;float l=std::sqrt(std::max(ds,1e-12f));o.normal=l>1e-5f?d*(1.f/l):Vec2{circle.position.x>=box.position.x?1.f:-1.f,0};o.penetration=r-l;o.point=q;return true;}
bool PhysicsWorld::collide(const Body2D&a,const Body2D&b,Contact2D&o)const{o.a=a.id;o.b=b.id;o.sensor=a.sensor||b.sensor;if(a.shape.type==ShapeType::Box&&b.shape.type==ShapeType::Box)return boxBox(a,b,o);if(a.shape.type==ShapeType::Circle&&b.shape.type==ShapeType::Circle)return circleCircle(a,b,o);if(a.shape.type==ShapeType::Box)return boxCircle(a,b,o);Contact2D t;if(!boxCircle(b,a,t))return false;o.normal=t.normal*-1.f;o.penetration=t.penetration;o.point=t.point;return true;}
void PhysicsWorld::solveContacts(){contacts_.clear();for(size_t i=0;i<bodies_.size();++i)for(size_t j=i+1;j<bodies_.size();++j){auto&a=bodies_[i];auto&b=bodies_[j];if(!canCollide(a,b))continue;Contact2D c;if(!collide(a,b,c))continue;contacts_.push_back(c);if(c.sensor)continue;Body2D*dyn=nullptr;if(a.inverseMass>0&&b.inverseMass==0)dyn=&a;else if(b.inverseMass>0&&a.inverseMass==0)dyn=&b;else if(a.inverseMass>0&&b.inverseMass>0)dyn=(a.inverseMass>=b.inverseMass?&a:&b);if(!dyn)continue;float inv=dyn->inverseMass;dyn->position+=c.normal*(c.penetration+0.01f);float vn=dot(dyn->velocity,c.normal);if(vn<0){float e=dyn->material.restitution;dyn->velocity-=c.normal*((1+e)*vn);float tangentV=dyn->velocity.x*c.normal.y-dyn->velocity.y*c.normal.x;float friction=std::clamp(dyn->material.friction,0.f,1.f);dyn->velocity-=Vec2{-c.normal.y,c.normal.x}*(tangentV*friction);}if(c.normal.y<-.5f)dyn->grounded=true;wake(*dyn);}}
void PhysicsWorld::sleeping(Body2D&b,float dt){if(b.type!=BodyType::Dynamic)return;constexpr float V2=.01f;if(len2(b.velocity)<V2&&len2(b.force)<V2)b.sleepTime+=dt;else b.sleepTime=0;if(b.sleepTime>.5f)b.awake=false;}
void PhysicsWorld::tick(float dt){for(auto&b:bodies_)integrate(b,dt);for(int pass=0;pass<2;++pass)solveContacts();for(auto&b:bodies_)sleeping(b,dt);}
void PhysicsWorld::step(float dt){std::lock_guard<std::mutex>g(mutex_);accumulator_+=clampf(dt,0,0.25f);int n=0;while(accumulator_>=fixedStep&&n++<maxSubSteps){tick(fixedStep);accumulator_-=fixedStep;}}
bool PhysicsWorld::raycast(Vec2 o,Vec2 d,float maxD,RayHit2D&hit)const{std::lock_guard<std::mutex>g(mutex_);d=norm(d);float best=maxD;bool found=false;for(const auto&b:bodies_){if(b.id==INVALID_BODY)continue;auto A=aabb(b);float tx1=(A.min.x-o.x)/(std::abs(d.x)>1e-8f?d.x:1e-8f),tx2=(A.max.x-o.x)/(std::abs(d.x)>1e-8f?d.x:1e-8f);float ty1=(A.min.y-o.y)/(std::abs(d.y)>1e-8f?d.y:1e-8f),ty2=(A.max.y-o.y)/(std::abs(d.y)>1e-8f?d.y:1e-8f);float tmin=std::max(std::min(tx1,tx2),std::min(ty1,ty2)),tmax=std::min(std::max(tx1,tx2),std::max(ty1,ty2));if(tmax>=std::max(0.f,tmin)&&tmin<best){best=tmin;found=true;hit.body=b.id;hit.fraction=best/maxD;hit.point=o+d*best;hit.normal={std::abs(hit.point.x-A.min.x)<.01f?-1.f:std::abs(hit.point.x-A.max.x)<.01f?1.f:0, std::abs(hit.point.y-A.min.y)<.01f?-1.f:std::abs(hit.point.y-A.max.y)<.01f?1.f:0};}}return found;}
std::vector<BodyId> PhysicsWorld::queryAabb(Aabb2D box)const{std::lock_guard<std::mutex>g(mutex_);std::vector<BodyId>r;for(const auto&b:bodies_)if(b.id!=INVALID_BODY&&aabb(b).overlaps(box))r.push_back(b.id);return r;}
void PhysicsWorld::clear(){std::lock_guard<std::mutex>g(mutex_);bodies_.clear();contacts_.clear();accumulator_=0;nextId_=1;}
void NativeRuntime::reset(){world.clear();world.createBody(200,200,BodyType::Dynamic);} void NativeRuntime::step(float dt){world.step(dt);} std::vector<float>NativeRuntime::transforms()const{std::vector<float>r;for(const auto&b:world.queryAabb({{-1e9f,-1e9f},{1e9f,1e9f}})){auto*p=world.body(b);r.insert(r.end(),{p->position.x,p->position.y,p->shape.type==ShapeType::Circle?p->shape.radius*2:p->shape.size.x,p->shape.type==ShapeType::Circle?p->shape.radius*2:p->shape.size.y});}return r;}
}
